name             'my-ant'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures my-ant'
long_description 'Installs/Configures my-ant'
version          '0.1.0'
depends		'ant' 
depends		'maven' 
